version: "1.0"

services:
  xml-parsing-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: xml-parsing-rest-api:latest
    container_name: xml-parsing-mysql-app
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS
    networks:
      - xml-mysql

  mysql-db:
    image: mysql:latest
    container_name: mysqldb
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: xml_parsing
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - xml-mysql

networks:
  xml-mysql:

volumes:
  mysql-data:
